In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [3]:
house_data = pd.read_csv(r"D:\GENEL\SPRINGBOARD\PROJECTS\CAPSTONE PROJECTS\CAPSTONE PROJECT-1\kc_house_data.csv\kc_house_data.csv", parse_dates = ['date'])

In [4]:
house_data.head()

id       date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520 2014-10-13  221900.0         3       1.00         1180   
1  6414100192 2014-12-09  538000.0         3       2.25         2570   
2  5631500400 2015-02-25  180000.0         2       1.00          770   
3  2487200875 2014-12-09  604000.0         4       3.00         1960   
4  1954400510 2015-02-18  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view     ...      grade  sqft_above  \
0      5650     1.0           0     0     ...          7        1180   
1      7242     2.0           0     0     ...          7        2170   
2     10000     1.0           0     0     ...          6         770   
3      5000     1.0           0     0     ...          7        1050   
4      8080     1.0           0     0     ...          8        1680   

   sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
0              0      1955             0    98178  47.5112 -122.257   
1            400      1951          1991    98125  47.7210 -122.319   
2              0      1933             0    98028  47.7379 -122.233   
3            910      1965             0    98136  47.5208 -122.393   
4              0      1987             0    98074  47.6168 -122.045   

   sqft_living15  sqft_lot15  
0           1340        5650  
1           1690        7639  
2           2720        8062  
3           1360        5000  
4           1800        7503  

[5 rows x 21 columns]

In [5]:
house_data.info() # There are 21613 rows and there is no null values.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
id               21613 non-null int64
date             21613 non-null datetime64[ns]
price            21613 non-null float64
bedrooms         21613 non-null int64
bathrooms        21613 non-null float64
sqft_living      21613 non-null int64
sqft_lot         21613 non-null int64
floors           21613 non-null float64
waterfront       21613 non-null int64
view             21613 non-null int64
condition        21613 non-null int64
grade            21613 non-null int64
sqft_above       21613 non-null int64
sqft_basement    21613 non-null int64
yr_built         21613 non-null int64
yr_renovated     21613 non-null int64
zipcode          21613 non-null int64
lat              21613 non-null float64
long             21613 non-null float64
sqft_living15    21613 non-null int64
sqft_lot15       21613 non-null int64
dtypes: datetime64[ns](1), float64(5), int64(15)
memory usage: 3.5 MB


In [6]:
house_data.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='object')

#### Columns:
**id:** A notation for a house  
**date:** Date house was sold  
**price:** Price is prediction target  
**bedrooms:** Number of Bedrooms/House  
**bathrooms:** Number of bathrooms/House  
**sqft_living:** Square footage of the home  
**sqft_lot:** Square footage of the lot  
**floorsTotal:** Floors (levels) in house  
**waterfront:** House which has a view to a waterfront  
**view:** Has been viewed  
**condition:** How good the condition is ( Overall )  
**grade:** Overall grade given to the housing unit, based on King County grading system  
**sqft_above:** Square footage of house apart from basement  
**sqft_basement:** Square footage of the basement  
**yr_built:** Built Year  
**yr_renovated:** Year when house was renovated  
**zipcode:** Zip Code  
**lat:** Latitude coordinate  
**long:** Longitude coordinate  
**sqft_living15:** Living room area in 2015(implies-- some renovations) This might or might not have affected the lotsize area  
**sqft_lot15:** LotSize area in 2015(implies-- some renovations)  

In [7]:
len(house_data.id.unique())

21436

In [8]:
house_data_duplicates = house_data[house_data.duplicated('id')]
house_data_duplicates #There are 177 dublicated rows.

id       date      price  bedrooms  bathrooms  sqft_living  \
94     6021501535 2014-12-23   700000.0         3       1.50         1580   
314    4139480200 2014-12-09  1400000.0         4       3.25         4290   
325    7520000520 2015-03-11   240500.0         2       1.00         1240   
346    3969300030 2014-12-29   239900.0         4       1.00         1000   
372    2231500030 2015-03-24   530000.0         4       2.25         2180   
718    8820903380 2015-01-02   730000.0         6       2.25         2660   
824     726049190 2015-02-18   431000.0         3       1.00         1810   
837    8682262400 2015-05-13   419950.0         2       1.75         1350   
1086   9834200885 2015-04-20   550000.0         4       2.50         2080   
1129   8062900070 2015-02-13   369000.0         5       1.50         2550   
1203   1231000510 2015-05-04   510000.0         3       1.75         1490   
1235   6117501820 2015-04-28   435000.0         2       1.00          790   
1451   2228900270 2015-02-12   302000.0         2       1.00         1010   
1465   3630120700 2015-01-07   765000.0         3       3.25         3190   
1577   7888000390 2015-04-01   235000.0         3       1.00         1060   
1865   2143700830 2015-03-12   370000.0         4       2.50         2100   
2039   3395040550 2015-04-29   320000.0         3       2.50         1530   
2127   4345000510 2015-04-28   325000.0         3       2.50         1800   
2494   9407110710 2015-02-26   322000.0         3       1.75         1510   
2497      1000102 2015-04-22   300000.0         6       3.00         2400   
2503   1781500435 2015-02-25   575000.0         3       1.75         1580   
2532   1232000810 2015-03-26   537000.0         3       2.50         1400   
2565   7856400240 2015-02-11  1650000.0         4       3.00         3900   
2632   7983000200 2015-02-25   250000.0         3       1.00         1300   
2977   9136103130 2015-05-12   685000.0         2       1.50         1090   
3034   5083000375 2015-03-19   235000.0         3       1.00         1310   
3299   7409700215 2015-03-13   921500.0         3       1.50         1900   
3541   1823049202 2015-01-07   326000.0         6       1.50         1930   
3624   2767602141 2014-12-22   650000.0         3       1.50         1380   
3757   1254200015 2015-04-08   625000.0         3       2.50         2260   
...           ...        ...        ...       ...        ...          ...   
16013  5536100020 2015-05-12  1190000.0         3       2.00         2160   
16672  9250900104 2015-04-10   496000.0         5       1.75         2110   
16815     7200179 2015-04-24   175000.0         2       1.00          840   
17067  8651402750 2015-04-30   219950.0         3       1.50         1210   
17134  6143000020 2015-04-06   299000.0         3       1.75         1910   
17205  4139440480 2014-12-01   796500.0         3       2.75         2590   
17281  2473380920 2015-02-27   339000.0         5       2.50         1720   
17291  1974300020 2015-02-18   624900.0         4       2.50         2270   
17382   641900050 2015-02-06   499950.0         4       2.25         2160   
17483  7387500235 2015-03-17   363000.0         3       1.75         1960   
17581  1423049019 2015-03-31   220000.0         2       1.00          580   
17603   795000620 2014-12-15   124000.0         3       1.00         1080   
17604   795000620 2015-03-11   157000.0         3       1.00         1080   
17764  1630700361 2015-04-09   583500.0         4       1.75         2860   
17852  6791200120 2015-04-07   515000.0         3       2.25         1820   
18234  6751300375 2014-10-16   522500.0         3       1.00         1520   
18565  7657000540 2015-03-04   260000.0         4       1.00         1220   
18704  3558900590 2015-03-24   692500.0         6       1.75         2230   
18706  8121100395 2015-03-11   645000.0         4       1.50         1600   
18763  3332000615 2015-04-22   389000.0         3       1.00         1330   
18992  7856

In [9]:
house_data.drop_duplicates(['id'], keep = 'last', inplace=True) # There are 177 dublicated rows. I kept the last entries.

In [10]:
h_data = house_data
h_data.reset_index(drop=True, inplace=True)
h_data.info() 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21436 entries, 0 to 21435
Data columns (total 21 columns):
id               21436 non-null int64
date             21436 non-null datetime64[ns]
price            21436 non-null float64
bedrooms         21436 non-null int64
bathrooms        21436 non-null float64
sqft_living      21436 non-null int64
sqft_lot         21436 non-null int64
floors           21436 non-null float64
waterfront       21436 non-null int64
view             21436 non-null int64
condition        21436 non-null int64
grade            21436 non-null int64
sqft_above       21436 non-null int64
sqft_basement    21436 non-null int64
yr_built         21436 non-null int64
yr_renovated     21436 non-null int64
zipcode          21436 non-null int64
lat              21436 non-null float64
long             21436 non-null float64
sqft_living15    21436 non-null int64
sqft_lot15       21436 non-null int64
dtypes: datetime64[ns](1), float64(5), int64(15)
memory usage: 3.4 MB


In [11]:
h_data.isnull().any()

id               False
date             False
price            False
bedrooms         False
bathrooms        False
sqft_living      False
sqft_lot         False
floors           False
waterfront       False
view             False
condition        False
grade            False
sqft_above       False
sqft_basement    False
yr_built         False
yr_renovated     False
zipcode          False
lat              False
long             False
sqft_living15    False
sqft_lot15       False
dtype: bool

In [12]:
h_data.drop(['id', 'date', 'lat', 'long'], axis = 1, inplace=True) #Let's reduce the dataset by dropping columns that won't be used during the analysis.

In [13]:
h_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21436 entries, 0 to 21435
Data columns (total 17 columns):
price            21436 non-null float64
bedrooms         21436 non-null int64
bathrooms        21436 non-null float64
sqft_living      21436 non-null int64
sqft_lot         21436 non-null int64
floors           21436 non-null float64
waterfront       21436 non-null int64
view             21436 non-null int64
condition        21436 non-null int64
grade            21436 non-null int64
sqft_above       21436 non-null int64
sqft_basement    21436 non-null int64
yr_built         21436 non-null int64
yr_renovated     21436 non-null int64
zipcode          21436 non-null int64
sqft_living15    21436 non-null int64
sqft_lot15       21436 non-null int64
dtypes: float64(3), int64(14)
memory usage: 2.8 MB


In [14]:
len(h_data.zipcode.unique())

70

In [15]:
print(h_data.waterfront.unique())

[0 1]


In [16]:
print(h_data.view.unique())

[0 3 4 2 1]


In [17]:
print(h_data.condition.unique())

[3 5 4 1 2]


In [18]:
print(h_data.grade.unique())

[ 7  6  8 11  9  5 10 12  4  3 13  1]


In [19]:
print(h_data.bathrooms.unique())

[1.   2.25 3.   2.   4.5  1.5  2.5  1.75 2.75 3.25 4.   3.5  0.75 4.75
 5.   4.25 3.75 0.   1.25 5.25 6.   0.5  5.5  6.75 5.75 8.   7.5  7.75
 6.25 6.5 ]


In [20]:
print(h_data.bedrooms.unique())

[ 3  2  4  5  1  6  7  0  8  9 11 10 33]


In [21]:
h_data[h_data.bedrooms >= 10] # Most likely there is a mistake at the line which bedroom number is 33. 

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  \
8688    520000.0        11       3.00         3000      4960     2.0   
13195  1148000.0        10       5.25         4590     10920     1.0   
15025   650000.0        10       2.00         3610     11914     2.0   
15724   640000.0        33       1.75         1620      6000     1.0   
19085   660000.0        10       3.00         2920      3745     2.0   

       waterfront  view  condition  grade  sqft_above  sqft_basement  \
8688            0     0          3      7        2400            600   
13195           0     2          3      9        2500           2090   
15025           0     0          4      7        3010            600   
15724           0     0          5      7        1040            580   
19085           0     0          4      7        1860           1060   

       yr_built  yr_renovated  zipcode  sqft_living15  sqft_lot15  
8688       1918          1999    98106           1420        4960  
13195      2008             0    98004           2730       10400  
15025      1958             0    98006           2040       11914  
15724      1947             0    98103           1330        4700  
19085      1913             0    98105           1810        3745

In [22]:
indexNames = h_data[ h_data['bedrooms'] == 33 ].index
h_data.drop(indexNames , inplace=True)

h_data.reset_index(drop=True, inplace=True)

In [23]:
h_data[h_data.bedrooms >= 10]

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  \
8688    520000.0        11       3.00         3000      4960     2.0   
13195  1148000.0        10       5.25         4590     10920     1.0   
15025   650000.0        10       2.00         3610     11914     2.0   
19084   660000.0        10       3.00         2920      3745     2.0   

       waterfront  view  condition  grade  sqft_above  sqft_basement  \
8688            0     0          3      7        2400            600   
13195           0     2          3      9        2500           2090   
15025           0     0          4      7        3010            600   
19084           0     0          4      7        1860           1060   

       yr_built  yr_renovated  zipcode  sqft_living15  sqft_lot15  
8688       1918          1999    98106           1420        4960  
13195      2008             0    98004           2730       10400  
15025      1958             0    98006           2040       11914  
19084      1913             0    98105           1810        3745

In [24]:
h_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21435 entries, 0 to 21434
Data columns (total 17 columns):
price            21435 non-null float64
bedrooms         21435 non-null int64
bathrooms        21435 non-null float64
sqft_living      21435 non-null int64
sqft_lot         21435 non-null int64
floors           21435 non-null float64
waterfront       21435 non-null int64
view             21435 non-null int64
condition        21435 non-null int64
grade            21435 non-null int64
sqft_above       21435 non-null int64
sqft_basement    21435 non-null int64
yr_built         21435 non-null int64
yr_renovated     21435 non-null int64
zipcode          21435 non-null int64
sqft_living15    21435 non-null int64
sqft_lot15       21435 non-null int64
dtypes: float64(3), int64(14)
memory usage: 2.8 MB


In [26]:
h_data['waterfront'] = h_data['waterfront'].astype('category',ordered=True)
h_data['view'] = h_data['view'].astype('category',ordered=True)
h_data['condition'] = h_data['condition'].astype('category',ordered=True)
h_data['grade'] = h_data['grade'].astype('category',ordered=True)
h_data['zipcode'] = h_data['zipcode'].astype(str)

C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: specifying 'categories' or 'ordered' in .astype() is deprecated; pass a CategoricalDtype instead
  """Entry point for launching an IPython kernel.
C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: specifying 'categories' or 'ordered' in .astype() is deprecated; pass a CategoricalDtype instead
  
C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: specifying 'categories' or 'ordered' in .astype() is deprecated; pass a CategoricalDtype instead
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: specifying 'categories' or 'ordered' in .astype() is deprecated; pass a CategoricalDtype instead
  after removing the cwd from sys.path.


In [27]:
h_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21435 entries, 0 to 21434
Data columns (total 17 columns):
price            21435 non-null float64
bedrooms         21435 non-null int64
bathrooms        21435 non-null float64
sqft_living      21435 non-null int64
sqft_lot         21435 non-null int64
floors           21435 non-null float64
waterfront       21435 non-null category
view             21435 non-null category
condition        21435 non-null category
grade            21435 non-null category
sqft_above       21435 non-null int64
sqft_basement    21435 non-null int64
yr_built         21435 non-null int64
yr_renovated     21435 non-null int64
zipcode          21435 non-null object
sqft_living15    21435 non-null int64
sqft_lot15       21435 non-null int64
dtypes: category(4), float64(3), int64(9), object(1)
memory usage: 2.2+ MB
